export const DRAWER_NAVIGATOR = 'DRAWER_NAVIGATOR';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROJECT_DETAILS_SCREEN = 'PROJECT_DETAILS_SCREEN';
export const TOPICS_DETAILS_SCREEN = 'TOPICS_DETAILS_SCREEN';

export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
