export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROJECT_DETAILS_SCREEN = 'PROJECT_DETAILS_SCREEN';
export const TOPICS_DETAILS_SCREEN = 'TOPICS_DETAILS_SCREEN';

export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const NEW_USER_PROFILE_SCREEN = 'NEW_USER_PROFILE_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const INTRO_SCREEN_1 = 'INTRO_SCREEN_1';
export const INTRO_SCREEN_2 = 'INTRO_SCREEN_2';
